# Form implementation generated from reading ui file 'cet_path.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(475, 396)
        Dialog.setStyleSheet("QPushButton{\n"
"    background-color:rgb(85, 85, 255);\n"
"    color:rgb(255, 255, 255)\n"
"}\n"
"*{\n"
"    background-color:rgb(255, 255, 127)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setStyleSheet("*{\n"
"    font-size:15px;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_examID = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_examID.setObjectName("lineEdit_examID")
        self.horizontalLayout_2.addWidget(self.lineEdit_examID)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_subjectCode = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_subjectCode.setObjectName("lineEdit_subjectCode")
        self.horizontalLayout_3.addWidget(self.lineEdit_subjectCode)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lineEdit_mainNum = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_mainNum.setObjectName("lineEdit_mainNum")
        self.horizontalLayout_4.addWidget(self.lineEdit_mainNum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEdit_drawImg = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_drawImg.setObjectName("lineEdit_drawImg")
        self.horizontalLayout_5.addWidget(self.lineEdit_drawImg)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.pushButton_pic = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_pic.setObjectName("pushButton_pic")
        self.verticalLayout.addWidget(self.pushButton_pic)
        self.pushButton_student = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_student.setObjectName("pushButton_student")
        self.verticalLayout.addWidget(self.pushButton_student)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "CET数据生成器"))
        self.label.setText(_translate("Dialog", "请输入需要生成的考生数量："))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "请输入正整数"))
        self.label_2.setText(_translate("Dialog", "考试ID："))
        self.lineEdit_examID.setPlaceholderText(_translate("Dialog", "考试ID"))
        self.label_3.setText(_translate("Dialog", "科目代码："))
        self.lineEdit_subjectCode.setPlaceholderText(_translate("Dialog", "科目代码"))
        self.label_4.setText(_translate("Dialog", "大题号："))
        self.lineEdit_mainNum.setPlaceholderText(_translate("Dialog", "大题号"))
        self.label_5.setText(_translate("Dialog", "添加水印文字："))
        self.lineEdit_drawImg.setPlaceholderText(_translate("Dialog", "默认水印文字为作文"))
        self.pushButton_pic.setText(_translate("Dialog", "开始生成图片"))
        self.pushButton_student.setText(_translate("Dialog", "开始生成考生数据"))
