# Form implementation generated from reading ui file 'file_arrang.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(535, 455)
        Dialog.setStyleSheet("QPushButton{\n"
"    font-size:15px;\n"
"    font-weight:bold;\n"
"    background-color:rgb(85, 85, 255);\n"
"    color:rgb(255, 255, 255)\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setStyleSheet("*{\n"
"    font-size:16px;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.pushButton_chose = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_chose.setObjectName("pushButton_chose")
        self.horizontalLayout.addWidget(self.pushButton_chose)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_filepath = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_filepath.setStyleSheet("*{\n"
"    font-size:10px;\n"
"}")
        self.lineEdit_filepath.setObjectName("lineEdit_filepath")
        self.horizontalLayout_2.addWidget(self.lineEdit_filepath)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_arrang = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_arrang.setObjectName("pushButton_arrang")
        self.verticalLayout.addWidget(self.pushButton_arrang)
        self.pushButton_open = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_open.setObjectName("pushButton_open")
        self.verticalLayout.addWidget(self.pushButton_open)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "文件整理器"))
        self.label.setText(_translate("Dialog", "请选择要整理的目录："))
        self.pushButton_chose.setText(_translate("Dialog", "选择目录"))
        self.label_2.setText(_translate("Dialog", "已选择的目录："))
        self.pushButton_arrang.setText(_translate("Dialog", "开始整理"))
        self.pushButton_open.setText(_translate("Dialog", "打开目录"))
