# Form implementation generated from reading ui file 'password_generate.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PasswordGenerate(object):
    def setupUi(self, PasswordGenerate):
        PasswordGenerate.setObjectName("PasswordGenerate")
        PasswordGenerate.resize(470, 396)
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        PasswordGenerate.setFont(font)
        self.centralwidget = QtWidgets.QWidget(parent=PasswordGenerate)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_site = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_site.setObjectName("lineEdit_site")
        self.horizontalLayout.addWidget(self.lineEdit_site)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.checkBox_lower = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_lower.setObjectName("checkBox_lower")
        self.horizontalLayout_2.addWidget(self.checkBox_lower)
        self.checkBox_upper = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_upper.setObjectName("checkBox_upper")
        self.horizontalLayout_2.addWidget(self.checkBox_upper)
        self.checkBox_upc = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_upc.setObjectName("checkBox_upc")
        self.horizontalLayout_2.addWidget(self.checkBox_upc)
        self.checkBox_number = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox_number.setObjectName("checkBox_number")
        self.horizontalLayout_2.addWidget(self.checkBox_number)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.lineEdit_result = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.verticalLayout.addWidget(self.lineEdit_result)
        PasswordGenerate.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=PasswordGenerate)
        self.statusbar.setObjectName("statusbar")
        PasswordGenerate.setStatusBar(self.statusbar)

        self.retranslateUi(PasswordGenerate)
        QtCore.QMetaObject.connectSlotsByName(PasswordGenerate)

    def retranslateUi(self, PasswordGenerate):
        _translate = QtCore.QCoreApplication.translate
        PasswordGenerate.setWindowTitle(_translate("PasswordGenerate", "生成密码小程序"))
        self.label.setText(_translate("PasswordGenerate", "网站"))
        self.checkBox_lower.setText(_translate("PasswordGenerate", "小写字母"))
        self.checkBox_upper.setText(_translate("PasswordGenerate", "大写字母"))
        self.checkBox_upc.setText(_translate("PasswordGenerate", "标点符号"))
        self.checkBox_number.setText(_translate("PasswordGenerate", "数字"))
        self.pushButton.setText(_translate("PasswordGenerate", "生成密码数字"))
