# Form implementation generated from reading ui file 'IBMcalc.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_BmiCompute(object):
    def setupUi(self, BmiCompute):
        BmiCompute.setObjectName("BmiCompute")
        BmiCompute.resize(595, 478)
        BmiCompute.setStyleSheet("*{\n"
"    color:blue;\n"
"    font-size:15px;\n"
"}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(BmiCompute)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=BmiCompute)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_weight = QtWidgets.QLineEdit(parent=BmiCompute)
        self.lineEdit_weight.setObjectName("lineEdit_weight")
        self.horizontalLayout.addWidget(self.lineEdit_weight)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=BmiCompute)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_stature = QtWidgets.QLineEdit(parent=BmiCompute)
        self.lineEdit_stature.setObjectName("lineEdit_stature")
        self.horizontalLayout_2.addWidget(self.lineEdit_stature)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton = QtWidgets.QPushButton(parent=BmiCompute)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_3 = QtWidgets.QLabel(parent=BmiCompute)
        self.label_3.setStyleSheet("*{\n"
"    font-size: 10px;\n"
"    background-color:rgb(234, 255, 5);\n"
"}")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.horizontalLayout_3.setStretch(0, 7)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.label_result = QtWidgets.QLabel(parent=BmiCompute)
        self.label_result.setStyleSheet("*{\n"
"    background-color:rgb(255, 170, 255)\n"
"}")
        self.label_result.setObjectName("label_result")
        self.verticalLayout_2.addWidget(self.label_result)
        self.label_warning = QtWidgets.QLabel(parent=BmiCompute)
        self.label_warning.setStyleSheet("*{\n"
"    background-color:rgb(255, 170, 255);\n"
"    color:red;\n"
"}")
        self.label_warning.setObjectName("label_warning")
        self.verticalLayout_2.addWidget(self.label_warning)
        self.verticalLayout_2.setStretch(0, 8)
        self.verticalLayout_2.setStretch(1, 2)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(BmiCompute)
        QtCore.QMetaObject.connectSlotsByName(BmiCompute)

    def retranslateUi(self, BmiCompute):
        _translate = QtCore.QCoreApplication.translate
        BmiCompute.setWindowTitle(_translate("BmiCompute", "BMI计算程序"))
        self.label_2.setText(_translate("BmiCompute", "请输入体重(kg):"))
        self.label.setText(_translate("BmiCompute", "请输入身高(cm):"))
        self.pushButton.setText(_translate("BmiCompute", "计算BMI"))
        self.label_3.setText(_translate("BmiCompute", "我国体重指数正常范围是18.5～24千克/米²。\n"
"\n"
"体重指数是国际上常用的衡量人体胖瘦程度以及是否健康的一个标准。体重指数的公式为：体重指数（BMI）=体重（千克）/身高²（米²）。我国体重指数范围的意义：BMI＜18.5千克/米²为体重过低；18.5千克/米²≤BMI＜24千克/米²为正常；24千克/米²≤BMI＜28千克/米²为超重；BMI≥28千克/米²为肥胖。世界卫生组织把超重界定为体重指数等于或大于25千克/米²，肥胖界定为体重指数等于或大于30千克/米²。"))
        self.label_result.setText(_translate("BmiCompute", "您的计算结果是："))
        self.label_warning.setText(_translate("BmiCompute", "BMI:26,属于超重，您的理想体重是68kg"))
