# Form implementation generated from reading ui file 'phones_extras.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 489)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.plainTextEdit_extra = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_extra.setObjectName("plainTextEdit_extra")
        self.verticalLayout.addWidget(self.plainTextEdit_extra)
        self.pushButton_extra = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_extra.setObjectName("pushButton_extra")
        self.verticalLayout.addWidget(self.pushButton_extra)
        self.plainTextEdit_phones = QtWidgets.QPlainTextEdit(parent=Dialog)
        self.plainTextEdit_phones.setObjectName("plainTextEdit_phones")
        self.verticalLayout.addWidget(self.plainTextEdit_phones)
        self.pushButton_copy = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_copy.setObjectName("pushButton_copy")
        self.verticalLayout.addWidget(self.pushButton_copy)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "提取并复制手机号"))
        self.label.setText(_translate("Dialog", "请输入将要提取的内容："))
        self.pushButton_extra.setText(_translate("Dialog", "提取手机号"))
        self.pushButton_copy.setText(_translate("Dialog", "复制手机号"))
